const PRODUCTS = [
  {id:'mobile-cart',name:'Mobile Cart',category:'ready',kicker:'Best seller',price:799,was:1000,img:'project-03',badge:'PROMO',desc:'Mobile counter serba guna untuk event, F&B dan retail. Pilihan hitam atau putih, siap ruang branding.'},
  {id:'node-cart',name:'Node Cart',category:'ready',kicker:'Premium setup',price:899,was:1300,img:'project-06',badge:'PROMO',desc:'Bentuk kiosk lebih solid dengan storage dan presentation area yang lebih lengkap untuk operasi harian.'},
  {id:'poplite',name:'PopLite',category:'ready',kicker:'Lightweight',price:699,was:899,img:'project-10',badge:'PROMO',desc:'Pilihan lebih ringkas dan cepat setup untuk pop-up, bazar, event booth dan usahawan mobile.'},
  {id:'tanjak-go',name:'Tanjak Go',category:'ready',kicker:'Entry model',price:650,was:799,img:'project-11',badge:'PROMO',desc:'Model kompak dengan harga paling rendah dalam promo semasa, sesuai untuk mula berniaga tanpa heavy setup.'},
  {id:'corner-cart',name:'Corner / Custom Kiosk',category:'custom',kicker:'Made to order',price:null,img:'project-05',badge:'CUSTOM',desc:'Counter sudut, canopy, rounded corner atau layout khas. Design disesuaikan dengan flow dan brand bisnes.'},
  {id:'lightbox',name:'Lightbox',category:'custom',kicker:'Add-on',price:null,img:'project-02',badge:'ADD-ON',desc:'Signage bercahaya untuk naikkan visibility booth atau kiosk, terutama indoor mall dan event.'},
  {id:'standee',name:'Standee Signage',category:'custom',kicker:'Add-on',price:null,img:'project-04',badge:'ADD-ON',desc:'Freestanding signage untuk menu, promo, wayfinding atau visual brand di hadapan booth.'},
  {id:'branding',name:'Logo & Brand Finish',category:'custom',kicker:'Add-on',price:null,img:'project-09',badge:'BRANDING',desc:'Logo application dan finishing visual supaya cart terus nampak seperti outlet brand anda sendiri.'},
  {id:'event-cafe',name:'Event & Cafe Furniture',category:'legacy',kicker:'Furniture',price:null,img:'project-12',badge:'ENQUIRE',desc:'Furniture dan props untuk event, cafe dan commercial setup. Dibuat ikut spesifikasi dan kegunaan.'},
  {id:'storage',name:'Storage & Organizer',category:'legacy',kicker:'Furniture',price:null,img:'project-07',badge:'ENQUIRE',desc:'Storage dan organizer custom daripada koleksi furniture KIKA.U, tertakluk kepada model dan ketersediaan semasa.'},
  {id:'dining',name:'Dining Collection',category:'legacy',kicker:'Furniture',price:null,img:'project-08',badge:'ENQUIRE',desc:'Dining furniture custom dengan fokus pada fungsi, finishing dan saiz mengikut ruang.'}
];
const BANKS=[['ABB0233','Affin Bank'],['AGRO01','Agrobank / AGRONet'],['ABMB0212','Alliance Bank'],['AMBB0209','AmBank'],['BIMB0340','Bank Islam'],['BMMB0341','Bank Muamalat'],['BOCM01','Bank of China'],['BKRM0602','Bank Rakyat'],['BSN0601','BSN'],['BCBB0235','CIMB Clicks'],['CIT0219','Citibank'],['HLB0224','Hong Leong Bank'],['HSBC0223','HSBC'],['KFH0346','KFH'],['MB2U0227','Maybank2U'],['OCBC0229','OCBC Bank'],['PBB0233','Public Bank'],['RHB0218','RHB Bank'],['SCB0216','Standard Chartered'],['UOB0226','UOB Bank']];
const state={cart:JSON.parse(localStorage.getItem('kika-cart')||'{}'),filter:'all'};
const $=s=>document.querySelector(s);
const money=n=>`RM${Number(n).toLocaleString('en-MY')}`;
function renderProducts(){const grid=$('#productGrid');const list=PRODUCTS.filter(p=>state.filter==='all'||p.category===state.filter);grid.innerHTML=list.map(p=>`<article class="product-card"><div class="product-image"><div class="sprite sprite-${p.img.split('-')[1]}" role="img" aria-label="${p.name}"></div><span class="badge">${p.badge}</span></div><div class="product-body"><span class="product-kicker">${p.kicker}</span><h3 class="product-title">${p.name}</h3><p class="product-desc">${p.desc}</p><div class="product-bottom">${p.price?`<div class="price"><s>${money(p.was)}</s><strong>${money(p.price)}</strong></div><button class="add-btn" data-add="${p.id}" aria-label="Add ${p.name} to cart">+</button>`:`<div class="price"><strong>Quote</strong></div><a class="enquire-btn" target="_blank" rel="noopener" href="https://wa.me/601143776911?text=${encodeURIComponent('Hi KIKA.U, saya nak tanya pasal '+p.name)}">Tanya harga</a>`}</div></div></article>`).join('');}
function save(){localStorage.setItem('kika-cart',JSON.stringify(state.cart));renderCart();}
function add(id){state.cart[id]=(state.cart[id]||0)+1;save();openCart();}
function change(id,d){state.cart[id]=(state.cart[id]||0)+d;if(state.cart[id]<=0)delete state.cart[id];save();}
function cartEntries(){return Object.entries(state.cart).map(([id,qty])=>({p:PRODUCTS.find(x=>x.id===id),qty})).filter(x=>x.p&&x.p.price)}
function renderCart(){const entries=cartEntries();const count=entries.reduce((s,x)=>s+x.qty,0);$('#cartCount').textContent=count;$('#cartItems').innerHTML=entries.length?entries.map(({p,qty})=>`<div class="cart-row"><div class="cart-thumb sprite sprite-${p.img.split('-')[1]}"></div><div><strong>${p.name}</strong><small>${money(p.price)} / unit</small><div class="qty"><button data-dec="${p.id}">−</button><span>${qty}</span><button data-inc="${p.id}">+</button></div></div><button class="remove" data-remove="${p.id}">×</button></div>`).join(''):`<div class="empty-cart">Cart masih kosong.<br>Pilih model untuk mula.</div>`;const total=entries.reduce((s,x)=>s+x.p.price*x.qty,0);$('#subtotal').textContent=money(total);$('#checkoutBtn').disabled=!entries.length;}
function openCart(){ $('#cartDrawer').classList.add('open');$('#drawerBackdrop').classList.add('show');$('#cartDrawer').setAttribute('aria-hidden','false');}
function closeCart(){ $('#cartDrawer').classList.remove('open');$('#drawerBackdrop').classList.remove('show');$('#cartDrawer').setAttribute('aria-hidden','true');}
function openCheckout(){if(!cartEntries().length)return;closeCart();$('#checkoutItems').value=JSON.stringify(cartEntries().map(({p,qty})=>({id:p.id,qty})));$('#checkoutModal').classList.add('open');$('#modalBackdrop').classList.add('show');$('#checkoutModal').setAttribute('aria-hidden','false');}
function closeCheckout(){ $('#checkoutModal').classList.remove('open');$('#modalBackdrop').classList.remove('show');$('#checkoutModal').setAttribute('aria-hidden','true');}
function whatsappOrder(){const entries=cartEntries();if(!entries.length)return;const total=entries.reduce((s,x)=>s+x.p.price*x.qty,0);const lines=entries.map(x=>`• ${x.p.name} x${x.qty} = ${money(x.p.price*x.qty)}`).join('\n');const text=`Hi KIKA.U, saya nak order:\n${lines}\n\nSubtotal: ${money(total)}\nBoleh confirm stok, delivery dan lead time?`;window.open(`https://wa.me/601143776911?text=${encodeURIComponent(text)}`,'_blank');}
document.addEventListener('click',e=>{const a=e.target.closest('[data-add]');if(a)add(a.dataset.add);const inc=e.target.closest('[data-inc]');if(inc)change(inc.dataset.inc,1);const dec=e.target.closest('[data-dec]');if(dec)change(dec.dataset.dec,-1);const rem=e.target.closest('[data-remove]');if(rem){delete state.cart[rem.dataset.remove];save()}const fil=e.target.closest('.filter');if(fil){document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));fil.classList.add('active');state.filter=fil.dataset.filter;renderProducts();}});
$('#openCart').onclick=openCart;$('#closeCart').onclick=closeCart;$('#drawerBackdrop').onclick=closeCart;$('#checkoutBtn').onclick=openCheckout;$('#closeCheckout').onclick=closeCheckout;$('#modalBackdrop').onclick=closeCheckout;$('#whatsappOrder').onclick=whatsappOrder;
$('#bankSelect').innerHTML='<option value="">Pilih bank</option>'+BANKS.map(([id,n])=>`<option value="${id}">${n}</option>`).join('');
$('#gallery').innerHTML=[1,2,3,4,5,6,7,9,10,11,12].map((n,i)=>`<figure class="gallery-card"><div class="sprite sprite-${n}" role="img" aria-label="KIKA.U customer cart project"></div></figure>`).join('');
renderProducts();renderCart();
